# Change these first
owner: 37397398371280
repo: Website-Status

sites:
  - name: Home Page
    url: https://game-idiots.github.io/website/
  - name: Soundboard Page
    url: https://game-idiots.github.io/website/sb.html
  - name: Thermal
    url: https://game-idiots.github.io/website/thermal.html
  - name: Code Playground
    url: https://game-idiots.github.io/website/Code-Playground.html
  - name: Today's Security Code
    url: https://game-idiots.github.io/website/Todays-Security-Code.html
  - name: Soundboard Plans
    url: https://game-idiots.github.io/website/Soundboard-Plans.html
  - name: Abandoned Server
    url: https://game-idiots.github.io/website/Abandoned-Server.html
  - name: Leaks Page
    url: https://game-idiots.github.io/website/Leaks/Leaks.html
  - name: Self Destruct
    url: https://game-idiots.github.io/website/Self-Destruct.html
  - name: Self Destruct (Past)
    url: https://game-idiots.github.io/website/Past/Self-Destruct-Past.html
  - name: Self Destruct (Future)
    url: https://game-idiots.github.io/website/Future/Self-Destruct-Future.html
  - name: Game Idiots Systems
    url: https://game-idiots.github.io/website/Game-Idiots-Systems.html
  - name: About Page
    url: https://game-idiots.github.io/website/About.html
    
status-website:
  baseUrl: /Website-Status
  logoUrl: https://game-idiots.github.io/website/Assets/icon.svg
  name: Website Status
  introTitle: "**Game Idiots** Status"
  introMessage: Welome to the Game Idiots Website Status Page
  navbar:
    - title: Status
      href: /Website-Status
    - title: Website
      href: https://game-idiots.github.io/website/
      
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
