# Change these first
owner: 37397398371280
repo: Game-Idiots-Website-Status

sites:
  - name: Home Page
    url: https://game-idiots.github.io/website/
    maxResponseTime: 1000
  - name: Soundboard Page
    url: https://game-idiots.github.io/website/sb.html
    maxResponseTime: 1000
  - name: Thermal
    url: https://game-idiots.github.io/website/thermal.html
    maxResponseTime: 1000
  - name: Code Playground
    url: https://game-idiots.github.io/website/Code-Playground.html
    maxResponseTime: 1000
  - name: Today's Security Code
    url: https://game-idiots.github.io/website/Todays-Security-Code.html
    maxResponseTime: 1000
  - name: Soundboard Plans
    url: https://game-idiots.github.io/website/Soundboard-Plans.html
    maxResponseTime: 1000
  - name: Abandoned Server
    url: https://game-idiots.github.io/website/Abandoned-Server.html
    maxResponseTime: 1000
  - name: Leaks Page
    url: https://game-idiots.github.io/website/Leaks/Leaks.html
    maxResponseTime: 1000
  - name: Self Destruct
    url: https://game-idiots.github.io/website/Self-Destruct.html
    maxResponseTime: 1000
  - name: Self Destruct (Past)
    url: https://game-idiots.github.io/website/Past/Self-Destruct-Past.html
    maxResponseTime: 1000
  - name: Self Destruct (Future)
    url: https://game-idiots.github.io/website/Future/Self-Destruct-Future.html
    maxResponseTime: 1000
  - name: Game Idiots Systems
    url: https://game-idiots.github.io/website/Game-Idiots-Systems.html
    maxResponseTime: 1000
  - name: About Page
    url: https://game-idiots.github.io/website/About.html
    maxResponseTime: 1000
  - name: Colten Sus Website Domain For Game Idiots (Game Idiots | gameidiots.coltensus.com)
    url: gameidiots.coltensus.com
    maxResponseTime: 1000
  - name: Colten Sus Website Domain For Game Idiots (GI | gi.coltensus.com)
    url: gi.coltensus.com
    maxResponseTime: 1000
  - name: Website Status Pages
    url: status.coltensus.com
    maxResponseTime: 1000
  - name: Colten Sus Website Status
    url: https://37397398371280.github.io/Colten-Sus-Website-Status/
    maxResponseTime: 1000
  - name: Game Idiots Website Status
    url: https://37397398371280.github.io/Game-Idiots-Website-Status/
    maxResponseTime: 1000
    
status-website:
  baseUrl: /Game-Idiots-Website-Status
  logoUrl: https://game-idiots.github.io/website/Assets/icon.svg
  name: Website Status
  introTitle: "**Game Idiots** Website Status"
  introMessage: Welome to the Game Idiots Website Status Page
  navbar:
    - title: Status
      href: /Game-Idiots-Website-Status
    - title: Website
      href: https://game-idiots.github.io/website/
      
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
