# Change these first
owner: 37397398371280
repo: Website-Status

sites:
  - name: Game Idiots Website
    url: https://game-idiots.github.io/website/
    
status-website:
  baseUrl: /Website-Status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Website Status
  introTitle: "**Game Idiots** Has lot of projects"
  introMessage: Welome to the Game Idiots Website Status Page
  navbar:
   - title: Status
      href: /
   - title: Website
      href: https://game-idiots.github.io/website/
      
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
